// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8aFTdV2ImarYA2C-bHjZAXskAJUMg4Rk',
    appId: '1:922100672523:web:3688912f56539de4413f0e',
    messagingSenderId: '922100672523',
    projectId: 'jit-gaye',
    authDomain: 'jit-gaye.firebaseapp.com',
    storageBucket: 'jit-gaye.appspot.com',
    measurementId: 'G-58Z4BVVYRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArxs4DQdVEKeUoB34-atxjSkbO3S0bgKA',
    appId: '1:922100672523:android:44259034736c079f413f0e',
    messagingSenderId: '922100672523',
    projectId: 'jit-gaye',
    storageBucket: 'jit-gaye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj9m0kBp3z8tDYCtk1-7QcVDmSPNZ-Us',
    appId: '1:922100672523:ios:c0a31a38c51fe3d1413f0e',
    messagingSenderId: '922100672523',
    projectId: 'jit-gaye',
    storageBucket: 'jit-gaye.appspot.com',
    iosClientId: '922100672523-75ei7ho6e5bjah19s85pejurd9d0utk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jitGaye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWj9m0kBp3z8tDYCtk1-7QcVDmSPNZ-Us',
    appId: '1:922100672523:ios:c0a31a38c51fe3d1413f0e',
    messagingSenderId: '922100672523',
    projectId: 'jit-gaye',
    storageBucket: 'jit-gaye.appspot.com',
    iosClientId: '922100672523-75ei7ho6e5bjah19s85pejurd9d0utk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jitGaye',
  );
}
